### ISSUE TITLE
Client Crash Mc-1.12.2 Forge 503

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Team-Fruit/ServerObserver#2]
https://gist.github.com/P3rf3ctXZer0/75391424fd8f113b6bbf6fce5b0f3967

**Comment by Kamesuta** [comment]
Thank you for your report.
In my environment (Twitch Client, Minecraft Changer, MultiMC) that problem did not occur.
Although it has not become a fundamental solution, I fixed it so that I can understand more detailed error.
Please tell me more detailed situation.
If it does not solve by any means, please abandon the use of universal version mod and consider using mod for each version.

---
[Original]
ご報告ありがとうございます。
私の環境(Twitch Client, Minecraft Changer, MultiMC)ではその問題は発生しませんでした。
根本的な解決にはなっていませんが、より詳しいエラーがわかるように修正しました。
より詳しい状況を教えてください。
どうしても解決しない場合は、ユニバーサルバージョンmodの使用を諦め、バージョンごとのmodの使用を検討してください。
